/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Badge } from "./Badge";
import { BadgeCountArgs } from "./BadgeCountArgs";
import { BadgeFindManyArgs } from "./BadgeFindManyArgs";
import { BadgeFindUniqueArgs } from "./BadgeFindUniqueArgs";
import { CreateBadgeArgs } from "./CreateBadgeArgs";
import { UpdateBadgeArgs } from "./UpdateBadgeArgs";
import { DeleteBadgeArgs } from "./DeleteBadgeArgs";
import { Completion } from "../../completion/base/Completion";
import { BadgeService } from "../badge.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Badge)
export class BadgeResolverBase {
  constructor(
    protected readonly service: BadgeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "read",
    possession: "any",
  })
  async _badgesMeta(
    @graphql.Args() args: BadgeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Badge])
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "read",
    possession: "any",
  })
  async badges(@graphql.Args() args: BadgeFindManyArgs): Promise<Badge[]> {
    return this.service.badges(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Badge, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "read",
    possession: "own",
  })
  async badge(
    @graphql.Args() args: BadgeFindUniqueArgs
  ): Promise<Badge | null> {
    const result = await this.service.badge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Badge)
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "create",
    possession: "any",
  })
  async createBadge(@graphql.Args() args: CreateBadgeArgs): Promise<Badge> {
    return await this.service.createBadge({
      ...args,
      data: {
        ...args.data,

        completion: args.data.completion
          ? {
              connect: args.data.completion,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Badge)
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "update",
    possession: "any",
  })
  async updateBadge(
    @graphql.Args() args: UpdateBadgeArgs
  ): Promise<Badge | null> {
    try {
      return await this.service.updateBadge({
        ...args,
        data: {
          ...args.data,

          completion: args.data.completion
            ? {
                connect: args.data.completion,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Badge)
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "delete",
    possession: "any",
  })
  async deleteBadge(
    @graphql.Args() args: DeleteBadgeArgs
  ): Promise<Badge | null> {
    try {
      return await this.service.deleteBadge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Completion, {
    nullable: true,
    name: "completion",
  })
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "read",
    possession: "any",
  })
  async getCompletion(
    @graphql.Parent() parent: Badge
  ): Promise<Completion | null> {
    const result = await this.service.getCompletion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
