/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BadgeService } from "../badge.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BadgeCreateInput } from "./BadgeCreateInput";
import { Badge } from "./Badge";
import { BadgeFindManyArgs } from "./BadgeFindManyArgs";
import { BadgeWhereUniqueInput } from "./BadgeWhereUniqueInput";
import { BadgeUpdateInput } from "./BadgeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BadgeControllerBase {
  constructor(
    protected readonly service: BadgeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Badge })
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBadge(@common.Body() data: BadgeCreateInput): Promise<Badge> {
    return await this.service.createBadge({
      data: {
        ...data,

        completion: data.completion
          ? {
              connect: data.completion,
            }
          : undefined,
      },
      select: {
        completion: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        image: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Badge] })
  @ApiNestedQuery(BadgeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async badges(@common.Req() request: Request): Promise<Badge[]> {
    const args = plainToClass(BadgeFindManyArgs, request.query);
    return this.service.badges({
      ...args,
      select: {
        completion: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        image: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Badge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async badge(
    @common.Param() params: BadgeWhereUniqueInput
  ): Promise<Badge | null> {
    const result = await this.service.badge({
      where: params,
      select: {
        completion: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        image: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Badge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBadge(
    @common.Param() params: BadgeWhereUniqueInput,
    @common.Body() data: BadgeUpdateInput
  ): Promise<Badge | null> {
    try {
      return await this.service.updateBadge({
        where: params,
        data: {
          ...data,

          completion: data.completion
            ? {
                connect: data.completion,
              }
            : undefined,
        },
        select: {
          completion: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          image: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Badge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Badge",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBadge(
    @common.Param() params: BadgeWhereUniqueInput
  ): Promise<Badge | null> {
    try {
      return await this.service.deleteBadge({
        where: params,
        select: {
          completion: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          image: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
